apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxdeploy
  name: nginxdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxdeploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}