apiVersion: v1
kind: Service
metadata:
  name: myghworkflow
  namespace: namespace-workflow-1716487752974
spec:
  type: LoadBalancer
  selector:
    app: myghworkflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000