name: "Build and push Super Mario Docker image with static tag to Docker Hub"

on:
  push:
    branches:
      - test


env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:

  build_push_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to ACR
        run: echo "${{ secrets.AZURE_PASSWORD }}" | docker login shubhasisacr.azurecr.io --username ${{ secrets.AZURE_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t sonarbuild:${{ env.VERSION }} .
          docker tag sonarbuild:${{ env.VERSION }} shubhasisacr.azurecr.io/sonarbuild:${{ env.VERSION }}
          docker push shubhasisacr.azurecr.io/sonarbuild:1.0