name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  push:
    branches:
      - test

env:
  VERSION: $(( $(cat version.txt) + 1 ))
      
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Login to ACR
        run: echo "${{ secrets.AZURE_PASSWORD }}" | docker login shubhasisacr.azurecr.io --username ${{ secrets.AZURE_USERNAME }} --password-stdin
        
      - name: Get Docker Image from ACR
        run: |
          docker pull shubhasisacr.azurecr.io/sonarbuild:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar shubhasisacr.azurecr.io/sonarbuild:${{ env.VERSION }}
     
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'